apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - student-env-configmaps.yaml

commonLabels:
  app.kubernetes.io/part-of: retail-edge-ha-workshop
  app.kubernetes.io/component: showroom-config
