apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - udn-module1/
  - udn-module2/
  - udn-module3/

commonLabels:
  app.kubernetes.io/part-of: retail-edge-ha-workshop
  app.kubernetes.io/component: networking

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
