apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vm-microshift-gw-a.yaml
  - vm-microshift-gw-b.yaml
  - externalsecret-gw-a.yaml
  - externalsecret-gw-b.yaml

commonLabels:
  app.kubernetes.io/part-of: retail-edge-ha-workshop
  app.kubernetes.io/component: virtualmachines
  module: module2
