apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  # HyperConverged CR will be added after operator installs
  # - hyperconverged.yaml

commonLabels:
  app.kubernetes.io/part-of: retail-edge-ha-workshop
  app.kubernetes.io/component: operators
