# Cloud-init - RHEL HA Node 2
# Generated for 2 students | IP: 10.101.0.21

---
# Student 01 - Node 2 Cloud-init
apiVersion: v1
kind: Secret
metadata:
  name: rhel-ha-node2-cloudinit
  namespace: retail-edge-student-01
type: Opaque
stringData:
  userdata: |
    #cloud-config
    user: cloud-user
    password: redhat
    chpasswd:
      expire: false
    ssh_pwauth: true
    packages:
      - pacemaker
      - pcs
      - fence-agents-kubevirt
      - corosync
      - fence-agents-all
    runcmd:
      - systemctl enable --now pcsd
      - echo "redhat" | passwd --stdin hacluster
      - hostnamectl set-hostname rhel-ha-node2
      - nmcli con mod "Wired connection 2" ipv4.addresses 10.101.0.21/24
      - nmcli con mod "Wired connection 2" ipv4.method manual
      - nmcli con mod "Wired connection 2" connection.autoconnect yes
      - nmcli con up "Wired connection 2"
      - echo "10.101.0.20 rhel-ha-node1" >> /etc/hosts
      - echo "10.101.0.21 rhel-ha-node2" >> /etc/hosts

---
# Student 02 - Node 2 Cloud-init
apiVersion: v1
kind: Secret
metadata:
  name: rhel-ha-node2-cloudinit
  namespace: retail-edge-student-02
type: Opaque
stringData:
  userdata: |
    #cloud-config
    user: cloud-user
    password: redhat
    chpasswd:
      expire: false
    ssh_pwauth: true
    packages:
      - pacemaker
      - pcs
      - fence-agents-kubevirt
      - corosync
      - fence-agents-all
    runcmd:
      - systemctl enable --now pcsd
      - echo "redhat" | passwd --stdin hacluster
      - hostnamectl set-hostname rhel-ha-node2
      - nmcli con mod "Wired connection 2" ipv4.addresses 10.101.0.21/24
      - nmcli con mod "Wired connection 2" ipv4.method manual
      - nmcli con mod "Wired connection 2" connection.autoconnect yes
      - nmcli con up "Wired connection 2"
      - echo "10.101.0.20 rhel-ha-node1" >> /etc/hosts
      - echo "10.101.0.21 rhel-ha-node2" >> /etc/hosts
