apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vm-rhel-node1.yaml
  - vm-rhel-node2.yaml
  - cloudinit-node1.yaml
  - cloudinit-node2.yaml

commonLabels:
  app.kubernetes.io/part-of: retail-edge-ha-workshop
  app.kubernetes.io/component: virtualmachines
  module: module1
