apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: microshift-vrrp
spec:
  selector:
    matchLabels:
      module: microshift
  template:
    spec:
      config:
        - name: microshift-setup
          gitRef:
            repository: retail-edge-ha-workshop
            targetRevision: main
            path: fleet-configs/module2-microshift
