apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: pacemaker-ha
  labels:
    version: "4"
spec:
  selector:
    matchLabels:
      module: pacemaker
  template:
    metadata:
      labels:
        configVersion: "4"
    spec:
      config:
        - name: pacemaker-dashboard
          gitRef:
            repository: retail-edge-ha-workshop
            targetRevision: main
            path: fleet-configs/module1-pacemaker
