---
apiVersion: v1
kind: ImageStream
metadata:
  name: retail-edge-ha-bookbag
  namespace: retail-edge-workshop
  labels:
    app: bookbag
    app.kubernetes.io/part-of: retail-edge-ha-workshop

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: retail-edge-ha-bookbag
  namespace: retail-edge-workshop
  labels:
    app: bookbag
    app.kubernetes.io/part-of: retail-edge-ha-workshop
spec:
  output:
    to:
      kind: ImageStreamTag
      name: retail-edge-ha-bookbag:latest
  source:
    git:
      uri: https://github.com/tosin2013/retail-edge-ha-workshop.git
      ref: main
    contextDir: bookbag
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
